### PR TITLE
raster hpp

### PR DESCRIPTION
**Pull request by cinderbdt**
raster and test harness

### CODE REVIEW

**Review by dgpalmieri — COMMENTED** [review]
This looks like all the raster stuff, so nice work getting that all together!

If you're looking for some good examples of how to use doctest, Theng and Tailon's PR's are a great place to find some inspiration.

**Comment by cinderbdt** [comment]
Thanks for cleaning up the commits in this PR, @dgpalmieri . I'm working on some doctest stuff and I'll commit it soon.

**Review by cinderbdt — COMMENTED** [review]
This is not a complete close of the issue with all of its subtasks. More work to do with doctest.

**Review by dgpalmieri — APPROVED** [review]
Looks great!

**Pull request merged**
