### PR TITLE
Octree, ERR_MSG update

### PR DESCRIPTION
**Pull request by mattp0**
This pull request will close (insert issue number)
This is intended to meet a cpp 17 standard while maintaining same functionality.

### CODE REVIEW

**Comment by dgpalmieri** [comment]
If you're not too attached to Visual Studio, I would recommend CLion instead - I switched over after using VS for about a year and I've never looked back. I've had a bunch of problems working with VS, and it wouldn't surprise me if that's the culprit behind the issue

**Comment by cinderbdt** [comment]
> I've had a bunch of problems working with VS, and it wouldn't surprise me if that's the culprit behind the issue.

I used CLion when you recommended it last semester, @dgpalmieri and I liked it.  This semester, I'm sort of stuck using WSL2, vi, and gcc in a good old terminal.  Let's just say we were hoping for a quicker approval of vaccine for 5-11 year olds, so the development machine had to be re-purposed when that didn't happen.

It seemed like @mattp0 is pretty well-versed on VS and its cool integrations with WSL2 and other things.  I would hate to say that VS is **the** issue here, but it might be contributing. @mattp0 did you do Ctrl-K Ctrl-D or do you have some other plugin or formatting set up?

**Comment by mattp0** [comment]
> @mattp0 If you resolve the conflicts between the branches, you should find "Draft Pull Request" under the dropdown next to "Merge Pull Request". ~I would reccommend accepting your version of doctest over the one in the repo, as the only difference I can see is indenting.~ I should have just fixed the issue, since you and Tailon were both apparently at a different style of doctest.

I do not have an option to do a draft.

**Comment by mattp0** [comment]
To answer the question about the doc test. I used the raw link and pasted into my editor. Did not do anything else.

**Comment by dgpalmieri** [comment]
> I do not have an option to do a draft.

Yeah, that's my bad. I thought the option was there, but if you look under the "reviewers" section, you can click where it says "convert to draft" and that should do it

@cinderbdt If you're going to be in WSL, VSCode has a great WSL extension that gives you a better dev experience than regular VS (in my opinon). If you would rather stick with the vi life, I actually do almost all of my developing in [neovim](https://github.com/neovim/neovim), and I'd be happy to share my wsl configs with you! There are definitely ways to make life easier than using plain vi.

**Comment by cinderbdt** [comment]
Sure would like to see your neovim. Can try VS again soon and I have the WSL stuff installed but have not tried it.
My temporary keyboard has a tiny Escape key and I remapped Caps Lock already so at least I fixed that! 🤣

**Comment by cinderbdt** [comment]
I edited the Makefile so that this will merge.

**Comment by dgpalmieri** [comment]
@mattp0 was this ready to merge? I was under the impression that this was still a draft

**Pull request merged**
